const btsDate = [
    {
        artist: "BTS",
        type: "Group",
        songs :[  
            {title : "Dynamite", releaseDate: "2020-08-21", album: "BE"},
            {title : "Butter", releaseDate: "2021-05-21", album: "Butter"},
            {title : "Permission to Dance", releaseDate: "2021-07-09", album: "Butter"},
            {title : "Life Goes On", releaseDate: "2020-11-20", album: "BE"},
            {title : "Fake Love", releaseDate: "2018-05-18", album: "Love Yourself: Tear"},
            {title : "Blood Sweat & Tears", releaseDate: "2016-10-10", album: "Wings"},   
            {title : "Spring Day", releaseDate: "2017-02-13", album: "You Never Walk Alone"},
            {title : "Fire", releaseDate: "2016-05-02", album: "The Most Beautiful Moment in Life: Young Forever"},
            {title : "Dope", releaseDate: "2015-09-08", album: "The Most Beautiful Moment in Life, Part 1"},    
            {title : "I Need U", releaseDate: "2015-04-29", album: "The Most Beautiful Moment in Life, Part 1"},
            {title : "Run", releaseDate: "2015-11-30", album: "The Most Beautiful Moment in Life, Part 2"},
            {title : "Not Today", releaseDate: "2017-02-20", album: "You Never Walk Alone"},
            {title : "Save Me", releaseDate: "2016-05-22", album: "The Most Beautiful Moment in Life: Young Forever"},
            {title : "Anpanman", releaseDate: "2018-09-18", album: "Love Yourself: Answer"},
            {title : "Go Go", releaseDate: "2017-02-13", album: "You Never Walk Alone"},
            {title : "Euphoria", releaseDate: "2018-04-05", album: "Love Yourself: Answer"},
            {title : "Serendipity", releaseDate: "2017-09-08", album: "Love Yourself: Her"},
            {title : "Singularity", releaseDate: "2018-05-07", album: "Love Yourself: Tear"},
            {title : "Magic Shop", releaseDate: "2018-02-13", album: "Love Yourself: Tear"},
            {title : "Airplane pt.2", releaseDate: "2018-02-13", album: "Love Yourself: Tear"}, 
            {title : "IDOL", releaseDate: "2018-08-24", album: "Love Yourself: Answer"},     
            {title : "On", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Black Swan", releaseDate: "2020-01-17", album: "Map of the Soul: 7"},
            {title : "ON (feat. Sia)", releaseDate: "2020-02-28", album: "Map of the Soul: 7"},
            {title : "Dionysus", releaseDate: "2019-11-30", album: "Map of the Soul: Persona"},    
            {title : "Jamais Vu", releaseDate: "2019-11-18", album: "Map of the Soul: Persona"},
            {title : "Inner Child", releaseDate: "2020-02-21", album: "Map of the Soul: 7"}, 
            {title : "Stay Gold", releaseDate: "2020-06-19", album: "Map of the Soul: 7"},
            {title : "We Are Bulletproof: The Eternal", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},    
            {title : "Friends", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Moon", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Respect", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},    
            {title : "We Are Bulletproof: The Eternal", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "00:00 (Zero O'Clock)", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Louder than bombs", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "UGH!", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Cypher pt.4", releaseDate: "2017-11-17", album: "Love Yourself: Answer"},
            {title : "Ddaeng", releaseDate: "2018-12-07", album: "Love Yourself: Answer"},
            {title : "Outro: Tear", releaseDate: "2018-05-18", album: "Love Yourself: Tear"},
            {title : "Outro: Her", releaseDate: "2017-09-18", album: "Love Yourself: Her"},
            {title : "Outro: Ego", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Outro: Persona", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Outro: Wings", releaseDate: "2016-10-10", album: "Wings"},    
            {title : "Cypher pt.3", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Cypher pt.2", releaseDate: "2015-11-30", album: "The Most Beautiful Moment in Life, Part 2"},
            {title : "Cypher pt.1", releaseDate: "2015-04-29", album: "The Most Beautiful Moment in Life, Part 1"},
            {title : "Intro: Persona", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Boy With Luv (feat. Halsey)", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Make It Right (feat. Lauv)", releaseDate: "2019-10-18", album: "Map of the Soul: Persona"},
            {title : "My Universe (feat. Coldplay)", releaseDate: "2019-11-18", album: "Map of the Soul: Persona"},
            {title : "Just One Day", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "No More Dream", releaseDate: "2013-06-13", album: "2 Cool 4 Skool"},
            {title : "We On", releaseDate: "2013-06-13", album: "2 Cool 4 Skool"},
            {title : "N.O", releaseDate: "2013-09-11", album: "2 Cool 4 Skool"},
            {title : "Attack on Bangtan", releaseDate: "2013-09-11", album: "2 Cool 4 Skool"},
            {title : "Pied Piper", releaseDate: "2017-09-18", album: "Love Yourself: Answer"},
            {title : "Go Go", releaseDate: "2017-02-13", album: "You Never Walk Alone"},
            {title : "Blue & Grey", releaseDate: "2020-11-20", album: "BE"},
            {title : "Telepathy", releaseDate: "2020-11-20", album: "BE"},
            {title : "Silver Spoon", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Dis-ease", releaseDate: "2020-11-20", album: "BE"},
            {title : "Danger", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "Dimple", releaseDate: "2018-09-18", album: "Love Yourself: Answer"},
            {title : "Trivia: Seesaw", releaseDate: "2018-09-18", album: "Love Yourself: Answer"},
            {title : "For Youth", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Film out", releaseDate: "2021-11-20", album: "BE"},
            {title : "Stay", releaseDate: "2022-02-21", album: "BE"},
            {title : "Yet To Come (The Most Beautiful Moment)", releaseDate: "2022-06-10", album: "BE"},
            {title : "Best of Me", releaseDate: "2017-09-18", album: "Love Yourself: Answer"},
            {title : "Airplane pt.2", releaseDate: "2018-02-13", album: "Love Yourself: Tear"},
            {title : "Lights", releaseDate: "2019-06-07", album: "Map of the Soul: Persona"},
            {title : "MIC Drop (Steve Aoki Remix)", releaseDate: "2017-11-24", album: "Love Yourself: Answer"},
            {title : "Don`t Leave Me", releaseDate: "2017-09-18", album: "Love Yourself: Answer"},
            {title : "Your Eyes Tell", releaseDate: "2018-09-18", album: "Love Yourself: Answer"},
            {title : "Crystal Snow", releaseDate: "2017-12-13", album: "Love Yourself: Answer"},
            {title : "The Truth Untold (feat. Steve Aoki)", releaseDate: "2018-02-13", album: "Love Yourself: Tear"},
            {title : "Love Maze", releaseDate: "2018-02-13", album: "Love Yourself: Tear"},
            {title : "So What", releaseDate: "2018-09-18", album: "Love Yourself: Answer"},
            {title : "Hold Me Tight", releaseDate: "2015-04-29", album: "The Most Beautiful Moment in Life, Part 1"},
            {title : "Autumn Leaves", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Butterfly", releaseDate: "2015-11-30", album: "The Most Beautiful Moment in Life, Part 2"},
            {title : "Lost", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Young Forever", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Converse High", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Moving On", releaseDate: "2016-11-18", album: "Wings"},
            {title : "House of Cards", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Run", releaseDate: "2015-11-30", album: "The Most Beautiful Moment in Life, Part 2"},
            {title : "Love is Not Over", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Intro: Boy Meets Evil", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Begin", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Lie", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Stigma", releaseDate: "2016-10-10", album: "Wings"},
            {title : "First Love", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Reflection", releaseDate: "2016-10-10", album: "Wings"},
            {title : "MAMA", releaseDate: "2013-06-13", album: "2 Cool 4 Skool"},
            {title : "Awake", releaseDate: "2016-10-10", album: "Wings"},
            {title : "Lost", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Am I Wrong", releaseDate: "2016-11-18", album: "Wings"},
            {title : "21st Century Girl", releaseDate: "2016-11-18", album: "Wings"},
            {title : "2! 3!", releaseDate: "2016-11-18", album: "Wings"},
            {title : "Microcosmos", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Home", releaseDate: "2019-04-12", album: "Map of the Soul: Persona"},
            {title : "Interlude: Shadow", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Inner Child", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Intro: What Am I To Do", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "War of Hormone", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "Hip Hop Lover", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "Let Me Know", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "Rain", releaseDate: "2014-09-29", album: "Skool Luv Affair"},
            {title : "Interlude: What Are You Doing", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Could You Turn Off Your Phone", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Embarrassed", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "24/7", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Look Here", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Outro: Do You Think It Makes Sense?", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Like", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Spine Breaker", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Jump", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Tomorrow", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Outro: Propose", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Where You From", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
            {title : "Skit: Soulmate", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
                  

    ]
        
    },
   {
    artist: "Jean Jungkook",
    type: "Solo",
    songs :[
        {title : "Euphoria", releaseDate: "2018-04-05", album: "Love Yourself: Answer"},
        {title : "My Time", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
        {title : "Stay Alive", releaseDate: "2022-01-14", album: "BTS, The Best"},
        {title : "Still With You", releaseDate: "2020-06-13", album: "BTS, The Best"},
        {title : "Standing Next To You", releaseDate: "2022-02-11", album: "Golden"},
        {title : "Seven (feat. Latto)", releaseDate: "2023-07-14", album: "Golden"},
        {title : "3D (feat. Jack Harlow)", releaseDate: "2023-07-14", album: "Golden"},
        {title : "Closer to You", releaseDate: "2023-07-14", album: "Golden"},
        {title : "Yes or No", releaseDate: "2023-11-03", album: "Golden"},
        {title : "Please Don`t Change(feat. DJ Snake)", releaseDate: "2023-11-03", album: "Golden"},
        {title : "Hate", releaseDate: "2023-11-03", album: "Golden"},
        {title : "Somebody", releaseDate: "2023-11-03", album: "Golden"},
        {title : "Too Sad To Dance", releaseDate: "2023-11-03", album: "Golden"},
        {title : "My Time (Acoustic Mix)", releaseDate: "2020-02-21", album: "Map of the Soul: 7"},
        {title : "Shot Glass of Tears", releaseDate: "2020-11-03", album: "Golden"}]
   },
   {
    artist: "Min Yoongi (SUGA)",
    type: "Solo",
    songs :[   
        {title : "Agust D", releaseDate: "2016-08-15", album: "Agust D"},
        {title : "Give It To Me", releaseDate: "2016-08-15", album: "Agust D"},
        {title : "Skit: Dream, Reality", releaseDate: "2016-08-15", album: "Agust D"},
        {title : "724148", releaseDate: "2016-08-15", album: "Agust D"},
        {title : "The Last", releaseDate: "2016-08-15", album: "Agust D"},
        {title : "Tony Montana", releaseDate: "2016-08-15", album: "Agust D"},  
        {title : "Interlude: Set Me Free", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Daechwita", releaseDate: "2020-05-22", album: "D-2"},
        {title : "What Do You Think?", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Strange", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Interlude: Shadow", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Burn It", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Interlude: Set Me Free Pt.2", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Blueberry Eyes (feat. MAX)", releaseDate: "2020-05-22", album: "D-2"},
        {title : "People", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Snow Flower (feat. MAX)", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Interlude: My Time Is Now", releaseDate: "2020-05-22", album: "D-2"},
        {title : "Interlude: Dream, Reality", releaseDate: "2016-08-15", album: "Agust D"},
]},

{
   artist: "Kim Namjoon (RM)",
    type: "Solo",
    songs :[
        {title : "Voice", releaseDate: "2015-09-03", album: "RM"},
        {title : "Awakening", releaseDate: "2015-09-03", album: "RM"},
        {title : "Do You", releaseDate: "2015-09-03", album: "RM"},
        {title : "Monster", releaseDate: "2015-09-03", album: "RM"},
        {title : "Throw Away", releaseDate: "2015-09-03", album: "RM"},
        {title : "Joke", releaseDate: "2015-09-03", album: "RM"},
        {title : "God Rap", releaseDate: "2015-09-03", album: "RM"},
        {title : "Rush (feat. Krizz Kaliko)", releaseDate: "2015-09-03", album: "RM"},
        {title : "Life", releaseDate: "2015-09-03", album: "RM"},
        {title : "Adrift", releaseDate: "2015-09-03", album: "RM"},
        {title : "I believe", releaseDate: "2015-09-03", album: "RM"},
        {title : "Tokyo", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Seoul", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Moonchild", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Badbye (feat. eAeon)", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Uhgood (feat. Lil Cherry)", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Everythingoes (feat. NELL)", releaseDate: "2018-10-23", album: "Mono"},
        {title : "Forever Rain", releaseDate: "2018-10-23", album: "Mono"},

]},

{
    artist: "Kim Seokjin (JIN)",
    type: "Solo",
    songs :[
        {title : "I Need You", releaseDate: "2015-09-03", album: "JIN"},
        {title : "My Way", releaseDate: "2015-09-03", album: "JIN"},
        {title : "I'm Not Afraid", releaseDate: "2015-09-03", album: "JIN"},
        {title : "The Truth About Myself", releaseDate: "2015-09-03", album: "JIN"},
        {title : "The Truth About Myself (Acoustic Version)", releaseDate: "2015-09-03", album: "JIN"},
        {title : "The Truth About Myself (Remix)", releaseDate: "2015-09-03", album: "JIN"},
    ]},


    {
    artist: "Jung Hoseok (J-HOPE)",
    type: "Solo",
    songs :[  
        {title : "Hope World", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "P.O.P (Piece of Peace) pt.1", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Daydream", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Base Line", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Hangsang (feat. Supreme Boi)", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Airplane", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Blue Side (Outro)", releaseDate: "2018-03-02", album: "Hope World"},
        {title : "Chicken Noodle Soup (feat. Becky G)", releaseDate: "2019-09-27", album: "Hope World"},
    ]},

    {
    artist: "Park Jimin (JIMIN)",
    type: "Solo",
    songs :[
        {title : "Like Crazy", releaseDate: "2015-09-03", album: "JIMIN"},
        {title : "I'm Not Afraid", releaseDate: "2015-09-03", album: "JIMIN"},
        {title : "The Truth About Myself", releaseDate: "2015-09-03", album: "JIMIN"},
        {title : "The Truth About Myself (Acoustic Version)", releaseDate: "2015-09-03", album: "JIMIN"},
        {title : "The Truth About Myself (Remix)", releaseDate: "2015-09-03", album: "JIMIN"},
    ]},







];